/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaRequest from 'study-gaiajs/app/lib/request';


/**
 * path: /admin/super/permissionNode
 *
 * 新建权限项
 */
export default class AdminSuperPermissionNodeAddRequest extends GaiaRequest {
  static accessorName = 'AdminSuperPermissionNodeAdd';
  static path = '/admin/super/permissionNode';
  static method = 'POST';

  /**
   * PermissionNode数据
   *
   * @type any
   * @memberof AdminSuperPermissionNodeAdd
   */
  node: any;

  // tslint:disable-next-line: max-func-body-length
  constructor(params: any, ctx: Context) {
    super(params, ctx);
    const data: {
      [K: string]: any;
    } = {};

    
    if (ctx.request.body.hasOwnProperty('node')) {
      data.node = ctx.request.body.node;
    }
    

    const rules = {
      node: {
        type: 'object', required: true, },

    };

    try {
      ctx.validate(rules, data);
    } catch (err) {
      ctx.service.error.throwRequestValidateError(err);
    }

    Object.defineProperties(this, {
      node: { value: data.node },
    });

    Object.defineProperty(this, 'toJSON', {
      value: () => {
        return data;
      },
    });
  }
}
