/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaRequest from 'study-gaiajs/app/lib/request';


/**
 * path: /admin/permission
 *
 * 是否有权限项权限
 */
export default class AdminHasPermissionRequest extends GaiaRequest {
  static accessorName = 'AdminHasPermission';
  static path = '/admin/permission';
  static method = 'GET';

  /**
   * 权限项id
   *
   * @type string
   * @memberof AdminHasPermission
   */
  permission: string;

  // tslint:disable-next-line: max-func-body-length
  constructor(params: any, ctx: Context) {
    super(params, ctx);
    const data: {
      [K: string]: any;
    } = {};

    
    if (ctx.query.hasOwnProperty('permission')) {
      data.permission = ctx.query.permission;
    }
    

    const rules = {
      permission: {
        type: 'string', required: true, },

    };

    try {
      ctx.validate(rules, data);
    } catch (err) {
      ctx.service.error.throwRequestValidateError(err);
    }

    Object.defineProperties(this, {
      permission: { value: data.permission },
    });

    Object.defineProperty(this, 'toJSON', {
      value: () => {
        return data;
      },
    });
  }
}
