/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaRequest from 'study-gaiajs/app/lib/request';


/**
 * path: /admin/super/admin_user
 *
 * 删除管理员
 */
export default class AdminSuperUserDelRequest extends GaiaRequest {
  static accessorName = 'AdminSuperUserDel';
  static path = '/admin/super/admin_user';
  static method = 'DELETE';

  /**
   *
   * @type string
   * @memberof AdminSuperUserDel
   */
  username: string;

  // tslint:disable-next-line: max-func-body-length
  constructor(params: any, ctx: Context) {
    super(params, ctx);
    const data: {
      [K: string]: any;
    } = {};

    
    if (ctx.request.body.hasOwnProperty('username')) {
      data.username = ctx.request.body.username;
    }
    

    const rules = {
      username: {
        type: 'string', required: true, },

    };

    try {
      ctx.validate(rules, data);
    } catch (err) {
      ctx.service.error.throwRequestValidateError(err);
    }

    Object.defineProperties(this, {
      username: { value: data.username },
    });

    Object.defineProperty(this, 'toJSON', {
      value: () => {
        return data;
      },
    });
  }
}
