/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaRequest from '@gaiajs/gaiajs/app/lib/request';


/**
 * path: /admin/super/admin_user
 *
 * 创建管理员
 */
export default class AdminSuperUserAddRequest extends GaiaRequest {
  static accessorName = 'AdminSuperUserAdd';
  static path = '/admin/super/admin_user';
  static method = 'POST';

  /**
   *
   * @type string
   * @memberof AdminSuperUserAdd
   */
  username: string;

  /**
   *
   * @type string[]
   * @memberof AdminSuperUserAdd
   */
  roles?: string[];

  // tslint:disable-next-line: max-func-body-length
  constructor(params: any, ctx: Context) {
    super(params, ctx);
    const data: {
      [K: string]: any;
    } = {};

    
    if (ctx.request.body.hasOwnProperty('username')) {
      data.username = ctx.request.body.username;
    }
    
    if (ctx.request.body.hasOwnProperty('roles')) {
      data.roles = ctx.request.body.roles;
    }
    

    const rules = {
      username: {
        type: 'string', required: true, },
      roles: {
        type: 'array', required: false, itemType: 'string', rule:{
        type: 'string', required: false, }, },

    };

    try {
      ctx.validate(rules, data);
    } catch (err) {
      ctx.service.error.throwRequestValidateError(err);
    }

    Object.defineProperties(this, {
      username: { value: data.username },
      roles: { value: data.roles },
    });

    Object.defineProperty(this, 'toJSON', {
      value: () => {
        return data;
      },
    });
  }
}
