/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaResponse from 'study-gaiajs/app/lib/response';

/**
 *
 */
export default class AdminHasPermissionResponse extends GaiaResponse {
  /**
   *
   * @type { allow: boolean }
   * @memberof data
   */
  data: { allow: boolean };

  constructor(data: any, ctx?: Context) {
    super(data, ctx);

  }

  async dump(): Promise<any> {
    const [data,] = await Promise.all([(this.data && (await (async data => {const [allow,] = await Promise.all([data.allow,]) as [boolean,];return { allow, };})(this.data))),]) as [{ allow: boolean },];
    return { data, };
  }
}
