/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaResponse from '@gaiajs/gaiajs/app/lib/response';

/**
 *
 */
export default class AdminSuperInceptUserResponse extends GaiaResponse {
  /**
   *
   * @type boolean
   * @memberof success
   */
  success: boolean;

  /**
   *
   * @type string
   * @memberof info
   */
  info: string;

  constructor(data: any, ctx?: Context) {
    super(data, ctx);

  }

  async dump(): Promise<any> {
    const [success,info,] = await Promise.all([this.success,this.info,]) as [boolean,string,];
    return { success, info, };
  }
}
