/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaResponse from 'study-gaiajs/app/lib/response';

import AdminRole from '../types/AdminRole';
/**
 *
 */
export default class AdminSuperRoleEditResponse extends GaiaResponse {
  /**
   *
   * @type AdminRole
   * @memberof data
   */
  data: AdminRole;

  constructor(data: any, ctx?: Context) {
    super(data, ctx);

  }

  async dump(): Promise<any> {
    const [data,] = await Promise.all([((this.data) && (await (new AdminRole(await this.data, this.ctx)).dump())),]) as [AdminRole,];
    return { data, };
  }
}
