/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaResponse from '@gaiajs/gaiajs/app/lib/response';

import AdminUser from '../types/AdminUser';
/**
 *
 */
export default class AdminSuperUsersListResponse extends GaiaResponse {
  /**
   *
   * @type { count: number; users: AdminUser[] }
   * @memberof data
   */
  data: { count: number; users: AdminUser[] };

  constructor(data: any, ctx?: Context) {
    super(data, ctx);

  }

  async dump(): Promise<any> {
    const [data,] = await Promise.all([(this.data && (await (async data => {const [count,users,] = await Promise.all([data.count,(await Promise.all((await data.users || []).map(async item => (((item) && (await (new AdminUser(await item, this.ctx)).dump())))))),]) as [number,AdminUser[],];return { count, users, };})(this.data))),]) as [{ count: number; users: AdminUser[] },];
    return { data, };
  }
}
