/**
 * generated by template generator. don't modify it.
 *
 */

import { Context } from 'egg';
import GaiaResponse from 'study-gaiajs/app/lib/response';

import AdminUser from '../types/AdminUser';
/**
 *
 */
export default class AdminSuperUserRoleDelResponse extends GaiaResponse {
  /**
   *
   * @type AdminUser
   * @memberof data
   */
  data: AdminUser;

  constructor(data: any, ctx?: Context) {
    super(data, ctx);

  }

  async dump(): Promise<any> {
    const [data,] = await Promise.all([((this.data) && (await (new AdminUser(await this.data, this.ctx)).dump())),]) as [AdminUser,];
    return { data, };
  }
}
